project:
  type: website
  output-dir: docs  

website:
  title: "Bruno Nicenboim"
  site-url: "https://bruno.nicenboim.me"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: publications.qmd
        text: Publications and presentations
      - href: team.qmd
        text: Team        
      - href: software.qmd
        text: Software   
      - href: cv.qmd
        text: CV           
      - href: posts/index.qmd
        text: Posts
    right:
      - icon: rss
        href: posts/index.xml
        aria-label: RSS Feed
  
  page-footer:
    left: |
      Licensed under [MIT](https://github.com/bnicenboim/bnicenboim.github.io/blob/master/LICENSE)
    center: "Â© 2021-2026 Bruno Nicenboim"
    right: 
      - text: "License"
        href: LICENSE.qmd

format:
  html:
    code-fold: false
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    include-after-body: 
      - recent-posts.html
      - goatcounter.html
    
editor: source