project:
  type: website
  output-dir: docs  # <-- add this

website:
  title: "Bruno Nicenboim"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - href: publications.qmd
        text: Publications and presentations
      - href: team.qmd
        text: Team        
      - href: software.qmd
        text: Software   
      - href: cv.qmd
        text: CV           
      - href: posts/index.qmd
        text: Posts


format:
  html:
    code-fold: false
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-location: right
    include-after-body: recent-posts.html
    
editor: visual


